export const list = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/9n5e1vToDVnqz3hW10Jdlvmzpo0.jpg",
      id: 361743,
      title: "Top Gun: Maverick",
      original_language: "en",
      original_title: "Top Gun: Maverick",
      overview:
        "After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.",
      poster_path: "/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
      media_type: "movie",
      genre_ids: [28, 18],
      popularity: 2829.379,
      release_date: "2022-05-24",
      video: false,
      vote_average: 8.37,
      vote_count: 3152,
    },
    {
      adult: false,
      backdrop_path: "/Aa9TLpNpBMyRkD8sPJ7ACKLjt0l.jpg",
      id: 94997,
      name: "House of the Dragon",
      original_language: "en",
      original_name: "House of the Dragon",
      overview:
        "The prequel series finds the Targaryen dynasty at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires—real and imagined—crumble from such heights. In the case of the Targaryens, their slow fall begins almost 193 years before the events of Game of Thrones, when King Viserys Targaryen breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.",
      poster_path: "/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
      media_type: "tv",
      genre_ids: [18, 10759, 10765, 9648],
      popularity: 6378.432,
      first_air_date: "2022-08-21",
      vote_average: 8.806,
      vote_count: 720,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/hYZ4a0JvPETdfgJJ9ZzyFufq8KQ.jpg",
      id: 629176,
      title: "Samaritan",
      original_language: "en",
      original_title: "Samaritan",
      overview:
        "Thirteen year old Sam Cleary  suspects that his mysteriously reclusive neighbor Mr. Smith is actually the legendary vigilante Samaritan, who was reported dead 20 years ago. With crime on the rise and the city on the brink of chaos, Sam makes it his mission to coax his neighbor out of hiding to save the city from ruin.",
      poster_path: "/vwq5iboxYoaSpOmEQrhq9tHicq7.jpg",
      media_type: "movie",
      genre_ids: [28, 18, 878],
      popularity: 1884.133,
      release_date: "2022-08-25",
      video: false,
      vote_average: 6.927,
      vote_count: 466,
    },
    {
      adult: false,
      backdrop_path: "/lbLPVvgq16BD3IA6sIH3riu9ouO.jpg",
      id: 762504,
      title: "Nope",
      original_language: "en",
      original_title: "Nope",
      overview:
        "Residents in a lonely gulch of inland California bear witness to an uncanny, chilling discovery.",
      poster_path: "/AcKVlWaNVVVFQwro3nLXqPljcYA.jpg",
      media_type: "movie",
      genre_ids: [27, 9648, 878, 53],
      popularity: 3447.388,
      release_date: "2022-07-20",
      video: false,
      vote_average: 7.108,
      vote_count: 980,
    },
    {
      adult: false,
      backdrop_path: "/9GvhICFMiRQA82vS6ydkXxeEkrd.jpg",
      id: 92783,
      name: "She-Hulk: Attorney at Law",
      original_language: "en",
      original_name: "She-Hulk: Attorney at Law",
      overview:
        "Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered hulk.",
      poster_path: "/hJfI6AGrmr4uSHRccfJuSsapvOb.jpg",
      media_type: "tv",
      genre_ids: [35, 10765],
      popularity: 6271.999,
      first_air_date: "2022-08-18",
      vote_average: 7.4,
      vote_count: 492,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/xfNHRI2f5kHGvogxLd0C5sB90L7.jpg",
      id: 539681,
      title: "DC League of Super-Pets",
      original_language: "en",
      original_title: "DC League of Super-Pets",
      overview:
        "When Superman and the rest of the Justice League are kidnapped, Krypto the Super-Dog must convince a rag-tag shelter pack - Ace the hound, PB the potbellied pig, Merton the turtle and Chip the squirrel - to master their own newfound powers and help him rescue the superheroes.",
      poster_path: "/r7XifzvtezNt31ypvsmb6Oqxw49.jpg",
      media_type: "movie",
      genre_ids: [16, 28, 10751, 878, 35],
      popularity: 3945.6,
      release_date: "2022-07-27",
      video: false,
      vote_average: 7.56,
      vote_count: 300,
    },
    {
      adult: false,
      backdrop_path: "/7ZO9yoEU2fAHKhmJWfAc2QIPWJg.jpg",
      id: 766507,
      title: "Prey",
      original_language: "en",
      original_title: "Prey",
      overview:
        "When danger threatens her camp, the fierce and highly skilled Comanche warrior Naru sets out to protect her people. But the prey she stalks turns out to be a highly evolved alien predator with a technically advanced arsenal.",
      poster_path: "/ujr5pztc1oitbe7ViMUOilFaJ7s.jpg",
      media_type: "movie",
      genre_ids: [53, 28],
      popularity: 4155.432,
      release_date: "2022-08-02",
      video: false,
      vote_average: 8.02,
      vote_count: 3368,
    },
    {
      adult: false,
      backdrop_path: "/jauI01vUIkPA0xVsamGj0Gs1nNL.jpg",
      id: 507086,
      title: "Jurassic World Dominion",
      original_language: "en",
      original_title: "Jurassic World Dominion",
      overview:
        "Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history’s most fearsome creatures.",
      poster_path: "/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg",
      media_type: "movie",
      genre_ids: [12, 28, 878],
      popularity: 2415.162,
      release_date: "2022-06-01",
      video: false,
      vote_average: 7.089,
      vote_count: 3112,
    },
    {
      adult: false,
      backdrop_path: "/nmGWzTLMXy9x7mKd8NKPLmHtWGa.jpg",
      id: 438148,
      title: "Minions: The Rise of Gru",
      original_language: "en",
      original_title: "Minions: The Rise of Gru",
      overview:
        "A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.",
      poster_path: "/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg",
      media_type: "movie",
      genre_ids: [16, 12, 35, 14],
      popularity: 2218.182,
      release_date: "2022-06-29",
      video: false,
      vote_average: 7.7,
      vote_count: 1712,
    },
    {
      adult: false,
      backdrop_path: "/5FFpcmPzD5mhLom7bymZq7Py8eT.jpg",
      id: 862551,
      title: "Me Time",
      original_language: "en",
      original_title: "Me Time",
      overview:
        "With his family away, a devoted stay-at-home dad enjoys his first me time in years by joining his hard-partying old friend on a wild birthday adventure.",
      poster_path: "/bkjPoisqAavXUvtoirxTEcLLQyI.jpg",
      media_type: "movie",
      genre_ids: [35],
      popularity: 381.973,
      release_date: "2022-08-26",
      video: false,
      vote_average: 5.8,
      vote_count: 164,
    },
    {
      adult: false,
      backdrop_path: "/eqhKMZTLcieAvoH6CBqknTTfNby.jpg",
      id: 90802,
      name: "The Sandman",
      original_language: "en",
      original_name: "The Sandman",
      overview:
        "After years of imprisonment, Morpheus — the King of Dreams — embarks on a journey across worlds to find what was stolen from him and restore his power.",
      poster_path: "/q54qEgagGOYCq5D1903eBVMNkbo.jpg",
      media_type: "tv",
      genre_ids: [10765, 18],
      popularity: 1572.794,
      first_air_date: "2022-08-05",
      vote_average: 8.25,
      vote_count: 650,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/wDyM1lIIgK4RIDAgr8iuZe9N1cf.jpg",
      id: 755566,
      title: "Day Shift",
      original_language: "en",
      original_title: "Day Shift",
      overview:
        "An LA vampire hunter has a week to come up with the cash to pay for his kid's tuition and braces. Trying to make a living these days just might kill him.",
      poster_path: "/bI7lGR5HuYlENlp11brKUAaPHuO.jpg",
      media_type: "movie",
      genre_ids: [28, 14, 27, 35],
      popularity: 1901.237,
      release_date: "2022-08-10",
      video: false,
      vote_average: 6.913,
      vote_count: 784,
    },
    {
      adult: false,
      backdrop_path: "/6cpRpfD3isvluFwXDGSiDVyibPJ.jpg",
      id: 829560,
      title: "The Next 365 Days",
      original_language: "pl",
      original_title: "Kolejne 365 dni",
      overview:
        "Laura and Massimo's relationship hangs in the balance as they try to overcome trust issues while a tenacious Nacho works to push them apart.",
      poster_path: "/dlyzCeI8wojBsUWdkNdO5AXtmZq.jpg",
      media_type: "movie",
      genre_ids: [10749, 18],
      popularity: 1469.735,
      release_date: "2022-08-19",
      video: false,
      vote_average: 6.879,
      vote_count: 335,
    },
    {
      adult: false,
      backdrop_path: "/xyS0NgcQ2pbGWcwvSSu3xKEBhoO.jpg",
      id: 614934,
      title: "Elvis",
      original_language: "en",
      original_title: "Elvis",
      overview:
        "The life story of Elvis Presley as seen through the complicated relationship with his enigmatic manager, Colonel Tom Parker.",
      poster_path: "/qBOKWqAFbveZ4ryjJJwbie6tXkQ.jpg",
      media_type: "movie",
      genre_ids: [10402, 18, 36],
      popularity: 450.182,
      release_date: "2022-06-22",
      video: false,
      vote_average: 7.909,
      vote_count: 1274,
    },
    {
      adult: false,
      backdrop_path: "/dHei5YA1qyZfkW6UiOz0w3k2BSS.jpg",
      id: 760161,
      title: "Orphan: First Kill",
      original_language: "en",
      original_title: "Orphan: First Kill",
      overview:
        "After escaping from an Estonian psychiatric facility, Leena Klammer travels to America by impersonating Esther, the missing daughter of a wealthy family. But when her mask starts to slip, she is put against a mother who will protect her family from the murderous “child” at any cost.",
      poster_path: "/wSqAXL1EHVJ3MOnJzMhUngc8gFs.jpg",
      media_type: "movie",
      genre_ids: [27, 53],
      popularity: 656.238,
      release_date: "2022-07-27",
      video: false,
      vote_average: 7.137,
      vote_count: 364,
    },
    {
      adult: false,
      backdrop_path: "/vvObT0eIWGlArLQx3K5wZ0uT812.jpg",
      id: 616037,
      title: "Thor: Love and Thunder",
      original_language: "en",
      original_title: "Thor: Love and Thunder",
      overview:
        "After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now inexplicably wields Mjolnir as the Relatively Mighty Girl Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.",
      poster_path: "/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
      media_type: "movie",
      genre_ids: [28, 12, 14],
      popularity: 5207.555,
      release_date: "2022-07-06",
      video: false,
      vote_average: 6.8,
      vote_count: 2184,
    },
    {
      adult: false,
      backdrop_path: "/pdfCr8W0wBCpdjbZXSxnKhZtosP.jpg",
      id: 84773,
      name: "The Lord of the Rings: The Rings of Power",
      original_language: "en",
      original_name: "The Lord of the Rings: The Rings of Power",
      overview:
        "Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth. From the darkest depths of the Misty Mountains, to the majestic forests of Lindon, to the breathtaking island kingdom of Númenor, to the furthest reaches of the map, these kingdoms and characters will carve out legacies that live on long after they are gone.",
      poster_path: "/suyNxglk17Cpk8rCM2kZgqKdftk.jpg",
      media_type: "tv",
      genre_ids: [10765, 10759, 18],
      popularity: 669.726,
      first_air_date: "2022-09-01",
      vote_average: 6.32,
      vote_count: 25,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg",
      id: 634649,
      title: "Spider-Man: No Way Home",
      original_language: "en",
      original_title: "Spider-Man: No Way Home",
      overview:
        "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
      poster_path: "/uJYYizSuA9Y3DCs0qS4qWvHfZg4.jpg",
      media_type: "movie",
      genre_ids: [28, 12, 878],
      popularity: 1180.683,
      release_date: "2021-12-15",
      video: false,
      vote_average: 8.047,
      vote_count: 14898,
    },
    {
      adult: false,
      backdrop_path: "/nW5fUbldp1DYf2uQ3zJTUdachOu.jpg",
      id: 718789,
      title: "Lightyear",
      original_language: "en",
      original_title: "Lightyear",
      overview:
        "Legendary Space Ranger Buzz Lightyear embarks on an intergalactic adventure alongside a group of ambitious recruits and his robot companion Sox.",
      poster_path: "/ox4goZd956BxqJH6iLwhWPL9ct4.jpg",
      media_type: "movie",
      genre_ids: [16, 878, 12, 28, 10751],
      popularity: 1113.433,
      release_date: "2022-06-15",
      video: false,
      vote_average: 7.261,
      vote_count: 1922,
    },
    {
      adult: false,
      backdrop_path: "/wNKwOtq27yfN13SKKV07NwkpBA3.jpg",
      id: 80752,
      name: "See",
      original_language: "en",
      original_name: "See",
      overview:
        "A virus has decimated humankind. Those who survived emerged blind. Centuries later when twins are born with the mythic ability to see, their father must protect his tribe against a threatened queen.",
      poster_path: "/lKDIhc9FQibDiBQ57n3ELfZCyZg.jpg",
      media_type: "tv",
      genre_ids: [18, 10765, 10759],
      popularity: 654.634,
      first_air_date: "2019-11-01",
      vote_average: 8.242,
      vote_count: 1706,
      origin_country: ["US"],
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};
